### ISSUE TITLE
sqsurl

### ISSUE THREAD

**Issue by jack7531** [saluyi/tm-exam-1#1]
@saluyi 
Dear Saluyi
Can I have sqsurl?

**Comment by saluyi** [comment]
Hi @jack7531 
here is the url 
https://sqs.us-east-1.amazonaws.com/811317346284/gtoc-exam-queue

**Comment by jack7531** [comment]
@saluyi 
got it!
Sorry for uploaded sensitive info.

**Comment by saluyi** [comment]
Hi @jack7531 ,

We also apologize for something not clear in this exam.
Joe H Change will provide a new key and token to Renee.

**Comment by jack7531** [comment]
@saluyi 
Thank you.
I appreciate it.

**Comment by jack7531** [comment]
@saluyi 
AmazonSQSException:
The security token included in the request is invalid.
(Service: AmazonSQS; Status Code: 403; Error Code: InvalidClientTokenId; Request ID: 34c4aceb-15db-5e06-8843-fb72e677640a; Proxy: null)

Is the Access key ID and Secret access key still valid?

**Comment by jack7531** [comment]
@saluyi 
https://github.com/jack7531/tm-exam-1.git
